version: '3'
services:
  mongo:
    image: mongo:3
    ports:
      - "27019:27017"
    volumes:
      - ./volumes/mongo:/data/db
    logging:
      driver: none
  web:
    image: node:8
    ports:
      - "1337:1337"
    depends_on:
      - mongo
    volumes:
      - ./web:/app
    working_dir: /app
    environment:
      NODE_ENV: development
      # VERBOSE: 1
    command: sleep infinity
    # command: npm run dev
  front:
    image: node:8
    ports:
      - "3001:3001"
    volumes:
      - ./front:/app
    working_dir: /app
    environment:
      NODE_ENV: development
    command: sleep infinity
    # command: npm run dev
  nginx:
    image: nginx:1
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./video:/usr/share/nginx/video
      - ./nginx.conf:/etc/nginx/conf.d/nginx.conf
    logging:
      driver: none
  # mongobackup:
  #   image: requilence/mongodb-backup
  #   environment:
  #     MONGODB_HOST: mongo
  #     MONGODB_PORT: 27017
  #     INIT_BACKUP: 'yes'
  #     MAX_BACKUPS: 100
  #     CRON_TIME: 0 5 * * *
  #   volumes:
  #     - ./volumes/mongobackup:/backup
